version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - devops:/data/db

volumes:
  devops: